cc_binary(
    name = "rgxr",
    srcs = ["main.cc"],
    deps = [
        "@com_google_absl//absl/flags:flag",
        "@com_google_absl//absl/flags:parse",
        "@com_google_absl//absl/flags:usage",
        "@com_google_absl//absl/random",
        "@com_google_absl//absl/random:distributions",
        "@com_googlesource_code_re2//:re2",
    ],
)
